### ISSUE TITLE
Recursive include

### ISSUE THREAD

**Issue by edubart** [charlesnicholson/nanoprintf#116]
I was trying to bundle nanoprintf in a standalone big C file, but I am unable to do this because `nanoprintf.h` requires it self in this line:
```c
#include "nanoprintf.h"
```

Could the code be refactored so nanoprintf does not need to recursively include itself? This will give more freedom to save it under a different name, or along with many other single headers libraries as a big single header bundle.

**Comment by charlesnicholson** [comment]
Ah, merging the PR auto-closed it. Anyway:

Thanks for the report, you're totally right- self-including was an awful hack and I shouldn't have done it :) It was there mostly so I could give the unit tests access to the internal helper functions when npf was compiled in a separate translation unit. Anyway, it was a simple refactor that improved the quality of the code and hopefully helps you out as well.

Please give it a try and let me know if it fixes your issue.

**Comment by edubart** [comment]
I've tried, this fixes thanks!

However I've spot something that could be an issue for others, you do the implementation only if `NANOPRINTF_H_INCLUDED` is not defined, this mean things like this won't work:

```c
#include "nanoprintf.h"
#define NANOPRINTF_IMPLEMENTATION
#include "nanoprintf.h" /* it won't be actually implemented */
```

In some single headers library this is doable, this is not an issue for me because I will always define `NANOPRINTF_IMPLEMENTATION` upfront, but may be for others.

**Comment by charlesnicholson** [comment]
Glad to hear it works, and thanks also for the second issue :) It's a great point; there should be a test for this. I'll take a crack at it.

**Comment by charlesnicholson** [comment]
BTW I just fixed the second issue you raised, if it's useful to you. Thanks for the reports!
