### ISSUE TITLE
npf_vsnprintf writes beyond bufsz

### ISSUE THREAD

**Issue by arjanoskam** [charlesnicholson/nanoprintf#251]
When calling npf_vsnprintf() in order to write a limited number of characters (bufsz parameter) into the destination buffer, the function writes beyond the bufsz offset into the destination buffer.
The issue was found when using npf_vsnprintf() to write small pieces (50 chars) of a larger text buffer (>500 chars) to a FIFO before sending it to a UART. No format specifiers, just characters.

I would expect the function to write no more than bufsz chars into the destination buffer, because that buffer could be limited in size (the very reason for calling this function).

Currently npf_vsnprintf() simply calls npf_vpprintf(), which does not seem to consider the size of the destination buffer and just processes the entire format string. The option of putting a terminating 0 at the beginning or end (bufsz-1) of the buffer in case of overflow is not sufficient, because the overflow has already occurred and the memory following the destination buffer is corrupted. Also the return value n is still the result of the entire format string, but it should be at most bufsz.

**Comment by charlesnicholson** [comment]
Hi @arjanoskam, thanks for reporting this. `npf_vsnprintf` should behave as you expect, not writing more than `bufsz` bytes to the specified buffer. There's a unit test in `unit_snprintf.cc` that tests this behavior, but it's only one test and not exactly exhaustive:

```
  SUBCASE("doesn't write past end of buffer") {
    buf[3] = '*';
    REQUIRE(npf_snprintf(buf, 3, "abcd") == 4);
    REQUIRE(buf[0] == 'a');
    REQUIRE(buf[1] == 'b');
    REQUIRE(buf[2] == 'c');
    REQUIRE(buf[3] == '*');
  }
```

`npf_vsnprintf` does call `npf_vpprintf`, but the internal per-byte callback function is `npf_bufputc`, which (hopefully?) guards against buffer overrun. The string bounds are stored in an `npf_bufputc_ctx_t` struct that `npf_vsnprintf` creates on the stack and passes in as the "context" parameter:

```
void npf_bufputc(int c, void *ctx) {
  npf_bufputc_ctx_t *bpc = (npf_bufputc_ctx_t *)ctx;
  if (bpc->cur < bpc->len) { bpc->dst[bpc->cur++] = (char)c; }
}
```

So, of course it's possible that there's a bug here, but I'm not seeing it yet. If you can provide a simple repro case, I'd appreciate it and happily look into it.

**Comment by charlesnicholson** [comment]
A thought: is it possible that you're treating the return value as "the number of bytes actually written" instead of "the number of bytes that _would_ have been written if infinite space were available"?

**Comment by arjanoskam** [comment]
You are absolutely right, I was treating the return value as "the number of bytes actually written", assuming it would be max bufsz.
I used the return value for copying bytes into my UART FIFO, so that's where the corruption occurred.

Thanks for pointing this out to me, will teach me to spend more time reading documentation... ;-)

BTW this is a great library! I'm using it on an embedded system with limited RAM resources, and it saved me a lot of stack space for each RTOS task.

**Comment by charlesnicholson** [comment]
Ah, glad it was a simple answer! For what it's worth, I strongly dislike the return value convention as well, because it forces you to call `strlen` _after_ printing, just to figure out how long the string that was just printed ended up being.

A "better" design might be to return _both_- how long the formatted string would have been, and how many bytes were actually written. Unfortunately, because I wanted npf to adhere to the C Standard, I have to live with it :)

**Comment by anordal** [comment]
The test doesn't look right, though, if `npf_snprintf` is supposed to behave like snprintf: The difference between `strncpy` and `snprintf` is that `snprintf` is supposed to write one byte less than the buffer size, and always terminate (as long as you give it a buffer of at least one byte). That's why strncpy is useless.

**Comment by charlesnicholson** [comment]
@anordal I believe you're correct, thank you for pointing this out. I'll fix it ASAP!
