### ISSUE TITLE
Use in submodule https instead of ssh

### ISSUE THREAD

**Issue by akaeba** [charlesnicholson/nanoprintf#258]
Hi Charles,

the nanoprintf is really a nice module for embedded systems. Thanks for sharing the code. When i try to build my system in a CICD environment my runners struggle to clone your [test](https://github.com/charlesnicholson/nanoprintf-paland-conformance) submodule. Therefore, could you adjust your [.gitmodules](https://github.com/charlesnicholson/nanoprintf/blob/main/.gitmodules) that you replace: 

https://github.com/charlesnicholson/nanoprintf/blob/64333b34020789666c67aa5cc17468b0911d0f8f/.gitmodules#L3

this line by:

```
https://github.com/charlesnicholson/nanoprintf-paland-conformance.git
```

This would solve my clone issue and should have no influence - because it's a public repo. What do you think? If you like i can also prepare a PR.

Thanks for your help!

BR,
Andreas

**Comment by charlesnicholson** [comment]
Hey @akaeba, sure, I'd be happy to take a patch for it. Sorry for the inconvenience :)

Also, just FYI if it wasn't on your radar: You can build nanoprintf on the host without the mpaland suite if you like- It's a cmake configuration option that can be disabled. That can be faster + simpler if you're not making changes to nanoprintf. I understand wanting the whole thing to build + run + success though!

**Comment by akaeba** [comment]
done in #259

**Comment by charlesnicholson** [comment]
Merged, thanks for the PR!

**Comment by akaeba** [comment]
Thanks for merging :)
