### ISSUE TITLE
Version in nanoprintf.h

### ISSUE THREAD

**Issue by MCMattiaOetiker** [charlesnicholson/nanoprintf#260]
Hi,

thank you a lot for your work.

I'm using nanoprintf at work by copying and pasting the nanoprintf.h file inside my cpp project.

I noticed that inside the nanoprintf.h the version is not indicated. If I open the file inside my project I don't know what version nanoprintf is.

Would it be possible to add the version in the comment section of the nanopritnf.h file for future releases?

Thanks in advance for your time

**Comment by charlesnicholson** [comment]
Thanks for the suggestion; I think it's a great idea and I've almost done it a few times but have been lazy. I'll start doing it with the next release. :)
